

COLUMNS:
  species          :    object 
  island             :   object 
  culmen_length_mm   :  float64
  culmen_depth_mm   :   float64
  flipper_length_mm  :   float64
  body_mass_g        :    float64
  sex              :    object

TARGET_COLUMN:
  name : sex